In [1]:
import pandas as pd
import seaborn as sns

from ucimlrepo import fetch_ucirepo

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
import joblib

In [2]:
# df = pd.read_csv("facial-and-oral-temperature-data-from-a-large-set-of-human-subject-volunteers-1.0.0/

In [3]:
# fetch dataset 
infrared_thermography_temperature = fetch_ucirepo(id=925)

# features and targets
X = infrared_thermography_temperature.data.features 
y = infrared_thermography_temperature.data.targets 

print(infrared_thermography_temperature.metadata)
print(infrared_thermography_temperature.variables)

{'uci_id': 925, 'name': 'Infrared Thermography Temperature', 'repository_url': 'https://archive.ics.uci.edu/dataset/925/infrared+thermography+temperature+dataset', 'data_url': 'https://archive.ics.uci.edu/static/public/925/data.csv', 'abstract': 'The Infrared Thermography Temperature Dataset contains temperatures read from various locations of inferred images about patients, with the addition of oral temperatures measured for each individual. The 33 features consist of gender, age, ethnicity, ambiant temperature, humidity, distance, and other temperature readings from the thermal images. The dataset is intended to be used in a regression task to predict the oral temperature using the environment information as well as the thermal image readings. ', 'area': 'Health and Medicine', 'tasks': ['Regression'], 'characteristics': ['Tabular'], 'num_instances': 1020, 'num_features': 33, 'feature_types': ['Real', 'Categorical'], 'demographics': ['Gender', 'Age', 'Ethnicity'], 'target_col': ['aveOralF', 'aveOralM'], 'index_col': ['SubjectID'], 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2021, 'last_updated': 'Tue Dec 12 2023', 'dataset_doi': '10.13026/9ay4-2c37', 'creators': ['Quanzeng Wang', 'Yangling Zhou', 'Pejman Ghassemi', 'David McBride', 'J. Casamento', 'T. Pfefer', 'Quanzeng Wang', 'Yangling Zhou', 'Pejman Ghassemi', 'David McBride', 'J. Casamento', 'T. Pfefer'], 'intro_paper': {'ID': 343, 'type': 'NATIVE', 'title': 'Infrared Thermography for Measuring Elevated Body Temperature: Clinical Accuracy, Calibration, and Evaluation', 'authors': 'Quanzeng Wang, Yangling Zhou, Pejman Ghassemi, David McBride, J. Casamento, T. Pfefer', 'venue': 'Italian National Conference on Sensors', 'year': 2021, 'journal': None, 'DOI': None, 'URL': 'https://www.semanticscholar.org/paper/443b9932d295ca3a014e7d874b4bd77a33a276bd', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': None, 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': '- gender\n- age\n- ethnicity\n- ambiant temperature\n- humidity\n- distance\n- temperature readings from the thermal images', 'citation': None}, 'external_url': 'https://physionet.org/content/face-oral-temp-data/1.0.0/'}
           name     role         type demographic  \
0     SubjectID       ID  Categorical        None
1      aveOralF   Target   Continuous        None
2      aveOralM   Target   Continuous        None
3        Gender  Feature  Categorical      Gender
4           Age  Feature  Categorical         Age
5     Ethnicity  Feature  Categorical   Ethnicity
6         T_atm  Feature   Continuous        None
7      Humidity  Feature   Continuous        None
8      Distance  Feature   Continuous        None
9     T_offset1  Feature   Continuous        None
10    Max1R13_1  Feature   Continuous        None
11    Max1L13_1  Feature   Continuous        None
12  aveAllR13_1  Feature   Continuous        None
13  aveAllL13_1  Feature   Continuous        None
14        T_RC1  Feature   Continuous        None
15    T_RC_Dry1  Feature   Continuous        None
16    T_RC_Wet1  Feature   Continuous        None
17    T_RC_Max1  Feature   Continuous        None
18        T_LC1  Feature   Continuous        None
19    T_LC_Dry1  Feature   Continuous        None
20    T_LC_Wet1  Feature   Continuous        None
21    T_LC_Max1  Feature   Continuous        None
22         RCC1  Feature   Continuous        None
23         LCC1  Feature   Continuous        None
24   canthiMax1  Feature   Continuous        None
25  canthi4Max1  Feature   Continuous        None
26      T_FHCC1  Feature   Continuous        None
27      T_FHRC1  Feature   Continuous        None
28      T_FHLC1  Feature   Continuous        None
29      T_FHBC1  Feature   Continuous        None
30      T_FHTC1  Feature   Continuous        None
31    T_FH_Max1  Feature   Continuous        None
32   T_FHC_Max1  Feature   Continuous        None
33       T_Max1  Feature   Continuous        None
34        T_OR1  Feature   Continuous        None
35    T_OR_Max1  Feature   Continuous        None

                                          description units missing_values
0                                          Subject ID  None             no
1              Oral temperature measured in fast mode  None             no
2           Oral temperature measured in monitor mode  None             no
3                                      Male or Female  None             no
4                          Age ranges in categories\n  None             no
5   American Indian or Alaska Native, Asian, Black...  None             no
6                                 Ambiant temperature  None             no
7                                   Relative humidity  None             no
8       Distance between the subjects and the IRTs.    None             no
9   Temperature difference between the set and mea...  None             no
10  Max value of a circle with diameter of 13 pixe...  None             no
11  Max value of a circle with diameter of 13 pixe...  None             no
12  Average value of a circle with diameter of 13 ...  None             no
13  Average value of a circle with diameter of 13 ...  None             no
14  Average temperature of the highest four pixels...  None             no
15  Average temperature of the highest four pixels...  None             no
16  Average temperature of the highest four pixels...  None             no
17  Max value of a square of 24x24 pixels around t...  None             no
18  Average temperature of the highest four pixels...  None             no
19  Average temperature of the highest four pixels...  None             no
20  Average temperature of the highest four pixels...  None             no
21  Max value of a circle with diameter of 13 pixe...  None             no
22  Average value of a square of 3x3 pixels center...  None             no
23  Average value of a square of 3x3 pixels center...  None             no
24              Max value in the extended canthi area  None             no
25  Average temperature of the highest four pixels...  None             no
26  Average value in the center point of forehead,...  None             no
27  Average value in the right point of the forehe...  None             no
28  Average value in the left point of the forehea...  None             no
29  Average value in the bottom point of the foreh...  None             no
30  Average value in the top point of the forehead...  None             no
31  Maximum temperature within the extended forehe...  None             no
32  Max value in the center point of forehead, a s...  None             no
33  Maximum temperature within the whole face region.  None             no
34  Average temperature of the highest four pixels...  None             no
35       Maximum temperature within the mouth region.  None             no

In [4]:
y

      aveOralF  aveOralM
0        36.85     36.59
1        37.00     37.19
2        37.20     37.34
3        36.85     37.09
4        36.80     37.04
...        ...       ...
1015     36.95     36.99
1016     37.25     37.19
1017     37.35     37.59
1018     37.15     37.29
1019     37.05     37.19

[1020 rows x 2 columns]

In [5]:
X

,Gender,Age,Ethnicity,T_atm,Humidity,Distance,T_offset1,Max1R13_1,Max1L13_1,aveAllR13_1,...,T_FHCC1,T_FHRC1,T_FHLC1,T_FHBC1,T_FHTC1,T_FH_Max1,T_FHC_Max1,T_Max1,T_OR1,T_OR_Max1
0,Male,41-50,White,24.0,28.0,0.8,0.7025,35.0300,35.3775,34.4000,...,33.5775,33.4775,33.3725,33.4925,33.0025,34.5300,34.0075,35.6925,35.6350,35.6525
1,Female,31-40,Black or African-American,24.0,26.0,0.8,0.7800,34.5500,34.5200,33.9300,...,34.0325,34.0550,33.6775,33.9700,34.0025,34.6825,34.6600,35.1750,35.0925,35.1075
2,Female,21-30,White,24.0,26.0,0.8,0.8625,35.6525,35.5175,34.2775,...,34.9000,34.8275,34.6475,34.8200,34.6700,35.3450,35.2225,35.9125,35.8600,35.8850
3,Female,21-30,Black or African-American,24.0,27.0,0.8,0.9300,35.2225,35.6125,34.3850,...,34.4400,34.4225,34.6550,34.3025,34.9175,35.6025,35.3150,35.7200,34.9650,34.9825
4,Male,18-20,White,24.0,27.0,0.8,0.8950,35.5450,35.6650,34.9100,...,35.0900,35.1600,34.3975,34.6700,33.8275,35.4175,35.3725,35.8950,35.5875,35.6175
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,Female,21-25,Asian,25.7,50.8,0.6,1.2225,35.6425,35.6525,34.8575,...,35.1075,35.3475,35.4000,35.1375,35.2750,35.8525,35.7475,36.0675,35.6775,35.7100
1016,Female,21-25,White,25.7,50.8,0.6,1.4675,35.9825,35.7575,35.4275,...,35.3100,35.2175,35.2200,35.2075,35.0700,35.7650,35.5525,36.5000,36.4525,36.4900
1017,Female,18-20,Black or African-American,28.0,24.3,0.6,0.1300,36.4075,36.3400,35.8700,...,35.4350,35.2400,35.2275,35.3675,35.3425,36.3750,35.7100,36.5350,35.9650,35.9975
1018,Male,26-30,Hispanic/Latino,25.0,39.8,0.6,1.2450,35.8150,35.5250,34.2950,...,34.8400,35.0200,34.9250,34.7150,34.5950,35.4150,35.3100,35.8600,35.4150,35.4350
1019,Female,18-20,White,23.8,45.6,0.6,0.8675,35.7075,35.5825,34.8875,...,34.5475,34.6500,34.6700,34.2150,34.7100,35.1525,35.1175,35.9725,35.8900,35.9175

In [6]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 33 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Gender       1020 non-null   object
 1   Age          1020 non-null   object
 2   Ethnicity    1020 non-null   object
 3   T_atm        1020 non-null   float64
 4   Humidity     1020 non-null   float64
 5   Distance     1018 non-null   float64
 6   T_offset1    1020 non-null   float64
 7   Max1R13_1    1020 non-null   float64
 8   Max1L13_1    1020 non-null   float64
 9   aveAllR13_1  1020 non-null   float64
 10  aveAllL13_1  1020 non-null   float64
 11  T_RC1        1020 non-null   float64
 12  T_RC_Dry1    1020 non-null   float64
 13  T_RC_Wet1    1020 non-null   float64
 14  T_RC_Max1    1020 non-null   float64
 15  T_LC1        1020 non-null   float64
 16  T_LC_Dry1    1020 non-null   float64
 17  T_LC_Wet1    1020 non-null   float64
 18  T_LC_Max1    1020 non-null   float64
 19  RCC1         1020 non-null   float64
 20  LCC1         1020 non-null   float64
 21  canthiMax1   1020 non-null   float64
 22  canthi4Max1  1020 non-null   float64
 23  T_FHCC1      1020 non-null   float64
 24  T_FHRC1      1020 non-null   float64
 25  T_FHLC1      1020 non-null   float64
 26  T_FHBC1      1020 non-null   float64
 27  T_FHTC1      1020 non-null   float64
 28  T_FH_Max1    1020 non-null   float64
 29  T_FHC_Max1   1020 non-null   float64
 30  T_Max1       1020 non-null   float64
 31  T_OR1        1020 non-null   float64
 32  T_OR_Max1    1020 non-null   float64
dtypes: float64(30), object(3)
memory usage: 263.1+ KB

In [7]:
X["Distance"]

0       0.8
1       0.8
2       0.8
3       0.8
4       0.8
       ...
1015    0.6
1016    0.6
1017    0.6
1018    0.6
1019    0.6
Name: Distance, Length: 1020, dtype: float64

In [8]:
def convert_age(x):
    if "-" in x:
        a, b = x.split("-")
        return (int(a) + int(b)) / 2
    elif x == ">60":
        return 65
    return None

X["Age_num"] = X["Age"].apply(convert_age)

X = X.drop(columns=["Age"])

C:\Users\USER\AppData\Local\Temp\ipykernel_19216\3662988169.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X["Age_num"] = X["Age"].apply(convert_age)

In [9]:
X.nunique()

Gender           2
Ethnicity        6
T_atm           78
Humidity       353
Distance        33
T_offset1      467
Max1R13_1      581
Max1L13_1      567
aveAllR13_1    670
aveAllL13_1    628
T_RC1          592
T_RC_Dry1      589
T_RC_Wet1      575
T_RC_Max1      577
T_LC1          570
T_LC_Dry1      578
T_LC_Wet1      585
T_LC_Max1      570
RCC1           606
LCC1           616
canthiMax1     560
canthi4Max1    558
T_FHCC1        638
T_FHRC1        639
T_FHLC1        641
T_FHBC1        635
T_FHTC1        654
T_FH_Max1      558
T_FHC_Max1     611
T_Max1         540
T_OR1          583
T_OR_Max1      587
Age_num          8
dtype: int64

In [10]:
X = X.drop(columns=[col for col in X.columns if X[col].nunique() == 1])

In [11]:
X.isnull().sum()

Gender         0
Ethnicity      0
T_atm          0
Humidity       0
Distance       2
T_offset1      0
Max1R13_1      0
Max1L13_1      0
aveAllR13_1    0
aveAllL13_1    0
T_RC1          0
T_RC_Dry1      0
T_RC_Wet1      0
T_RC_Max1      0
T_LC1          0
T_LC_Dry1      0
T_LC_Wet1      0
T_LC_Max1      0
RCC1           0
LCC1           0
canthiMax1     0
canthi4Max1    0
T_FHCC1        0
T_FHRC1        0
T_FHLC1        0
T_FHBC1        0
T_FHTC1        0
T_FH_Max1      0
T_FHC_Max1     0
T_Max1         0
T_OR1          0
T_OR_Max1      0
Age_num        0
dtype: int64

In [12]:
X["Gender"] = X["Gender"].str.strip()
X["Ethnicity"] = X["Ethnicity"].str.replace("-", " ").str.strip()

X["Ethnicity"].unique()

array(['White', 'Black or African American', 'Asian', 'Multiracial',
       'Hispanic/Latino', 'American Indian or Alaskan Native'],
      dtype=object)

In [13]:
if "T_RC" in X.columns and "T_LC" in X.columns:
    X["Temp_diff_RC_LC"] = X["T_RC"] - X["T_LC"]

if "T_RC_Wet1" in X.columns and "T_LC_Wet1" in X.columns:
    X["Temp_diff_Wet"] = X["T_RC_Wet1"] - X["T_LC_Wet1"]

In [14]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 34 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Gender         1020 non-null   object
 1   Ethnicity      1020 non-null   object
 2   T_atm          1020 non-null   float64
 3   Humidity       1020 non-null   float64
 4   Distance       1018 non-null   float64
 5   T_offset1      1020 non-null   float64
 6   Max1R13_1      1020 non-null   float64
 7   Max1L13_1      1020 non-null   float64
 8   aveAllR13_1    1020 non-null   float64
 9   aveAllL13_1    1020 non-null   float64
 10  T_RC1          1020 non-null   float64
 11  T_RC_Dry1      1020 non-null   float64
 12  T_RC_Wet1      1020 non-null   float64
 13  T_RC_Max1      1020 non-null   float64
 14  T_LC1          1020 non-null   float64
 15  T_LC_Dry1      1020 non-null   float64
 16  T_LC_Wet1      1020 non-null   float64
 17  T_LC_Max1      1020 non-null   float64
 18  RCC1           1020 non-null   float64
 19  LCC1           1020 non-null   float64
 20  canthiMax1     1020 non-null   float64
 21  canthi4Max1    1020 non-null   float64
 22  T_FHCC1        1020 non-null   float64
 23  T_FHRC1        1020 non-null   float64
 24  T_FHLC1        1020 non-null   float64
 25  T_FHBC1        1020 non-null   float64
 26  T_FHTC1        1020 non-null   float64
 27  T_FH_Max1      1020 non-null   float64
 28  T_FHC_Max1     1020 non-null   float64
 29  T_Max1         1020 non-null   float64
 30  T_OR1          1020 non-null   float64
 31  T_OR_Max1      1020 non-null   float64
 32  Age_num        1020 non-null   float64
 33  Temp_diff_Wet  1020 non-null   float64
dtypes: float64(32), object(2)
memory usage: 271.1+ KB

In [15]:
numeric_cols = X.select_dtypes(include=["number"]).columns
categorical_cols = ["Gender", "Ethnicity"]

In [16]:
numeric_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="median")) 
])

categorical_pipeline = Pipeline([
    ("imputer", SimpleImputer(strategy="most_frequent")),
    ("onehot", OneHotEncoder(handle_unknown="ignore"))
])

preprocessor = ColumnTransformer([
    ("num", numeric_pipeline, numeric_cols),
    ("cat", categorical_pipeline, categorical_cols)
])

In [17]:
pipeline = Pipeline([
    ("preprocessing", preprocessor),
    ("model", RandomForestRegressor(
     n_estimators=500,
    max_depth=10,
    min_samples_split=5,
    min_samples_leaf=2,
    random_state=42,
    n_jobs=-1
))
])




linear_pipeline = Pipeline([
    ("preprocessing", preprocessor),
    ("model", LinearRegression())
])

In [18]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [19]:
pipeline.fit(X_train, y_train)
linear_pipeline.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='median'))]),
                                                  Index(['T_atm', 'Humidity', 'Distance', 'T_offset1', 'Max1R13_1', 'Max1L13_1',
       'aveAllR13_1', 'aveAllL13_1', 'T_RC1', 'T_RC_Dry1', 'T_RC_Wet1',
       'T_RC_Max1', 'T_LC1', 'T_LC_Dry1', 'T_LC_Wet1', 'T_LC_Max1', 'RCC1',
       'LCC1', 'canthiMax1', 'canthi4Max1', 'T_FHCC1', 'T_FHRC1', 'T_FHLC1',
       'T_FHBC1', 'T_FHTC1', 'T_FH_Max1', 'T_FHC_Max1', 'T_Max1', 'T_OR1',
       'T_OR_Max1', 'Age_num', 'Temp_diff_Wet'],
      dtype='object')),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['Gender', 'Ethnicity'])])),
                ('model', LinearRegression())])

In [20]:
score = pipeline.score(X_test, y_test)
print("R² score:", score)

R² score: 0.6342770080593352

In [21]:
linear_score = linear_pipeline.score(X_test, y_test)
print("Linear Regression R²:", linear_score)

Linear Regression R²: 0.6394578491818046

In [22]:
# df = pd.concat([X, y], axis=1)

# corr_matrix = df.select_dtypes(include=["number"]).corr()

# sns.heatmap(corr_matrix)

In [23]:
rf_score = pipeline.score(X_test, y_test)

print("Linear Regression R²:", linear_score)
print("Random Forest R²:", rf_score)

Linear Regression R²: 0.6394578491818046
Random Forest R²: 0.6342770080593355

In [24]:
# X_transformed = pd.DataFrame(
#     transform.fit_transform(X),
#     columns=transform.get_feature_names_out()
# )

In [25]:
# X_train, X_test, y_train, y_test = train_test_split(
#     # X_transformed, y, test_size=0.2, random_state=42
# )

In [26]:
linear_pipeline.predict(X_test)

array([[37.09063244, 37.11858579],
       [36.66858666, 36.42183677],
       [36.70203617, 36.99025666],
       [36.87511196, 36.73383847],
       [36.77283533, 36.70860669],
       [37.07378457, 37.01813056],
       [37.46289975, 37.86092872],
       [36.76435922, 36.63313027],
       [36.91247607, 36.75962826],
       [36.83416239, 36.79851239],
       [37.12038307, 37.18825787],
       [36.70605201, 36.66102049],
       [37.36112317, 37.42663795],
       [36.98973062, 36.92452478],
       [36.82785176, 36.880707  ],
       [37.06604775, 37.05523469],
       [37.18570273, 37.3020933 ],
       [37.29638524, 37.35173237],
       [37.48904264, 37.90384419],
       [36.89477913, 37.03121136],
       [36.92768351, 36.88924114],
       [36.66746847, 36.48655314],
       [36.96926137, 37.10091539],
       [36.99525487, 36.99639517],
       [36.867628  , 36.91290072],
       [36.86770366, 36.82620932],
       [37.41999692, 37.58041928],
       [36.80495221, 36.66095981],
       [36.96549287, 36.94027748],
       [36.57370022, 36.54994322],
       [37.17143274, 37.32700051],
       [36.60363783, 36.46373948],
       [36.99604669, 37.1256274 ],
       [37.61943922, 37.93496455],
       [37.24587191, 37.36052039],
       [37.15431043, 37.2842497 ],
       [36.64203253, 36.57901123],
       [37.10625987, 37.08903905],
       [36.6393236 , 36.65972923],
       [36.84696662, 36.86979496],
       [37.03641484, 37.15474281],
       [36.78327923, 36.51313877],
       [37.15544945, 37.32776993],
       [37.03279177, 37.01755117],
       [36.87199005, 36.95475441],
       [37.028324  , 37.09382614],
       [37.46818647, 37.98677035],
       [36.90451698, 36.98137232],
       [37.31126159, 37.39896086],
       [36.94507655, 36.86838742],
       [36.42880647, 36.27903929],
       [38.1626968 , 38.77006264],
       [37.36982804, 37.67172782],
       [37.35890587, 37.67017363],
       [36.760209  , 36.89845361],
       [36.83135765, 36.70959702],
       [37.0259034 , 37.13734908],
       [37.09347282, 37.19688203],
       [36.85753368, 36.85383282],
       [36.75551233, 36.68544755],
       [37.60817527, 37.96587292],
       [36.67628105, 36.63744209],
       [37.19080405, 37.23746284],
       [36.92378016, 36.97620775],
       [36.85470009, 36.84366619],
       [37.07322338, 37.10351853],
       [37.1838916 , 37.18337097],
       [37.31312376, 37.64633304],
       [37.03590344, 37.11679999],
       [36.84961155, 36.85162016],
       [37.159155  , 37.26904061],
       [36.6429501 , 36.49411581],
       [36.72288156, 36.76482531],
       [36.55371289, 36.50174104],
       [37.17713528, 37.28894973],
       [36.91335108, 36.99084881],
       [36.30391598, 35.94200036],
       [36.98996545, 37.07911537],
       [36.80866072, 36.85180213],
       [37.07332551, 37.13296219],
       [37.12705122, 37.25623475],
       [37.37372993, 37.61997904],
       [36.89334076, 36.82286948],
       [36.94658536, 37.08998705],
       [36.75531365, 36.6948783 ],
       [37.04686162, 37.03503652],
       [37.30917396, 37.59739981],
       [37.87218353, 38.32637861],
       [36.9922166 , 37.02070816],
       [36.9896731 , 37.02731277],
       [36.96190423, 36.88668326],
       [36.9286441 , 36.88342498],
       [36.78417286, 36.76805268],
       [36.75124855, 36.68517071],
       [36.84264916, 36.85227153],
       [37.52483245, 37.81259275],
       [37.08123374, 37.2051078 ],
       [36.7586821 , 36.69646412],
       [36.89084812, 36.7955086 ],
       [36.92199333, 37.00002434],
       [36.76197525, 36.81679439],
       [36.50640406, 36.34425103],
       [36.87648399, 36.89583069],
       [36.95943418, 36.97041388],
       [36.75302643, 36.68335995],
       [37.20021509, 37.26239037],
       [36.6767435 , 36.50139856],
       [36.39504225, 36.2060529 ],
       [37.03835484, 37.1236333 ],
       [37.07033898, 37.18144394],
       [37.13896412, 37.25174099],
       [37.06660335, 37.0846601 ],
       [36.98386019, 36.99837297],
       [36.90174095, 36.89908762],
       [37.06475809, 37.28161419],
       [37.0846731 , 37.13363763],
       [36.50188695, 36.21254087],
       [37.60508229, 37.90164558],
       [37.04727445, 37.15220462],
       [37.11290479, 37.0965257 ],
       [37.26372603, 37.4165483 ],
       [36.92077466, 37.01235027],
       [37.1038314 , 37.161065  ],
       [37.23435628, 37.42535126],
       [36.99257292, 37.03893389],
       [37.789696  , 38.08754077],
       [37.91402575, 38.417911  ],
       [36.82696985, 36.8155272 ],
       [36.8888774 , 36.83859527],
       [37.9500907 , 38.50153007],
       [36.85560925, 36.92100215],
       [37.11297429, 37.3556008 ],
       [37.93061973, 38.35081057],
       [36.92032996, 36.7156823 ],
       [37.25535148, 37.27737197],
       [36.83539598, 36.84576917],
       [36.84852145, 36.91831603],
       [37.08806044, 37.31869859],
       [37.01129255, 37.06953228],
       [36.83830451, 36.74808019],
       [37.01225494, 36.98391602],
       [36.70010642, 36.67983193],
       [36.82975368, 36.81666829],
       [36.79706814, 36.75645047],
       [36.65225865, 36.52996815],
       [36.98962298, 36.97422607],
       [37.19025278, 37.1906523 ],
       [37.04737836, 37.1288294 ],
       [36.96770614, 37.04014397],
       [36.94563781, 37.1072008 ],
       [36.63483507, 36.63978562],
       [36.69293152, 36.56062147],
       [36.57664844, 36.32624809],
       [37.18390545, 37.26579962],
       [36.89147019, 36.65761102],
       [37.99992218, 38.41345007],
       [37.14695519, 37.29945939],
       [36.84009411, 36.73503537],
       [36.60394067, 36.47057004],
       [36.96057059, 37.11524644],
       [36.87996912, 36.82648846],
       [37.63903993, 37.99348614],
       [36.64770073, 36.70670062],
       [36.72378834, 36.72606135],
       [37.38441932, 37.8477537 ],
       [36.79853183, 36.84756599],
       [37.13307532, 37.05171098],
       [36.63002359, 36.41227533],
       [37.05866497, 37.01712042],
       [37.06889278, 37.13161974],
       [37.28535361, 37.47806887],
       [37.11138081, 37.22696017],
       [36.81802286, 36.84510605],
       [36.47461827, 36.37926611],
       [36.44551105, 36.25746218],
       [37.22770341, 37.09124876],
       [36.95687228, 37.00987956],
       [37.34242389, 37.44777919],
       [37.4193607 , 37.59376781],
       [37.08215094, 37.10670291],
       [36.90200562, 36.73383484],
       [37.16519224, 37.27915617],
       [36.58089987, 36.45960886],
       [37.12044369, 37.12030793],
       [37.06936835, 37.1401241 ],
       [36.61661739, 36.53958814],
       [36.7989965 , 36.75075002],
       [37.07316403, 37.25892805],
       [37.3216698 , 37.47146641],
       [37.3866604 , 37.56015483],
       [36.5976073 , 36.66592176],
       [37.04448961, 37.04431486],
       [37.07100389, 37.03730972],
       [36.74749838, 36.86038997],
       [37.29793036, 37.35853132],
       [36.95785428, 36.98510091],
       [36.83509029, 36.8476576 ],
       [36.93242006, 36.85479487],
       [37.02924616, 37.13133573],
       [36.97889263, 36.97664673],
       [36.92532375, 36.90809159],
       [36.81137413, 36.92296589],
       [36.98960761, 37.05693159],
       [37.01338605, 37.11380873]])

In [27]:
joblib.dump(linear_pipeline, "linear_model.pkl")

['linear_model.pkl']